baseURL = "http://osaatcioglu.github.io/"
languageCode = "en-us"
title = "Ömer Saatcioglu"
theme = "hugo-dusk"
publishDir = "docs"

[[menu.main]]
  name = "Blog"
  weight = -70
  identifier = "main-posts"
  url = "/posts/"

[[menu.main]]
  name = "Projects"
  weight = -50
  identifier = "main-projects"
  url = "/projects/"   

[params]
  description = "The last theme you'll ever need. Maybe."
  github = "osaatcioglu"
  stackoverflow = "https://stackoverflow.com/users/40929/%C3%96mer"
  linkedin = "osaatcioglu"
  email = "osaatcioglu@gmail.com"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "http://i.huffpost.com/gen/4393678/images/o-THE-MATRIX-facebook.jpg"
