baseURL = "https://osaatcioglu.netlify.com"
languageCode = "en-us"
title = "Ömer Saatcioglu"
theme = "hugo-dusk"
publishDir = "public"

[[menu.main]]
  name = "Blog"
  weight = -70
  identifier = "main-posts"
  url = "/posts/"

[[menu.main]]
  name = "Projects"
  weight = -50
  identifier = "main-projects"
  url = "/projects/"   

[params]
  github = "osaatcioglu"
  stackoverflow = "https://stackoverflow.com/users/40929/%C3%96mer"
  linkedin = "osaatcioglu"
  email = "osaatcioglu@gmail.com"
